// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-my-ratings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_ratings_default = defineTool({
  name: "list_my_ratings",
  title: "List my album ratings",
  description: "List the signed-in user's album ratings from SoundVault, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max ratings to return (1-100)."),
    min_rating: z.number().int().min(1).max(10).optional().describe("Optional minimum rating filter (1-10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, min_rating }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from("album_ratings").select(
      "album_title, artist_name, rating, rated_at, album_deezer_id, cover_url"
    ).eq("user_id", ctx.getUserId()).order("rated_at", { ascending: false }).limit(limit);
    if (min_rating !== void 0) q = q.gte("rating", min_rating);
    const { data, error } = await q;
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { ratings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/rate-album.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var rate_album_default = defineTool2({
  name: "rate_album",
  title: "Rate an album",
  description: "Create or update an album rating (1-10) for the signed-in user. Requires the Deezer album id, album title, and artist name.",
  inputSchema: {
    album_deezer_id: z2.string().min(1).describe("Deezer album id (string)."),
    album_title: z2.string().min(1),
    artist_name: z2.string().min(1),
    rating: z2.number().int().min(1).max(10),
    cover_url: z2.string().url().optional()
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("album_ratings").upsert(
      {
        user_id: ctx.getUserId(),
        album_deezer_id: input.album_deezer_id,
        album_title: input.album_title,
        artist_name: input.artist_name,
        rating: input.rating,
        cover_url: input.cover_url ?? null,
        rated_at: (/* @__PURE__ */ new Date()).toISOString()
      },
      { onConflict: "user_id,album_deezer_id" }
    ).select().single();
    if (error) {
      return {
        content: [{ type: "text", text: error.message }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: `Rated "${input.album_title}" by ${input.artist_name}: ${input.rating}/10`
        }
      ],
      structuredContent: { rating: data }
    };
  }
});

// src/lib/mcp/tools/search-music.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^4.4.3";
var search_music_default = defineTool3({
  name: "search_music",
  title: "Search music",
  description: "Search for artists, albums, or tracks on Deezer (the catalog SoundVault uses).",
  inputSchema: {
    query: z3.string().min(1).describe("Search text."),
    type: z3.enum(["artist", "album", "track"]).default("album").describe("What to search for."),
    limit: z3.number().int().min(1).max(25).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, type, limit }) => {
    const url = `https://api.deezer.com/search/${type}?q=${encodeURIComponent(query)}&limit=${limit}`;
    const res = await fetch(url);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Deezer error: ${res.status}` }],
        isError: true
      };
    }
    const json = await res.json();
    if (json.error) {
      return {
        content: [{ type: "text", text: json.error.message ?? "Deezer error" }],
        isError: true
      };
    }
    const results = (json.data ?? []).map((item) => ({
      id: String(item.id),
      title: item.title ?? item.name,
      artist: item.artist?.name,
      album: item.album?.title,
      cover: item.album?.cover_medium ?? item.cover_medium ?? item.picture_medium
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_profile_default = defineTool4({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in user's SoundVault profile with a summary of how many albums they have rated.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return {
        content: [{ type: "text", text: "Not authenticated." }],
        isError: true
      };
    }
    const sb = supabaseForUser3(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile }, { count }] = await Promise.all([
      sb.from("profiles").select("*").eq("user_id", userId).maybeSingle(),
      sb.from("album_ratings").select("*", { count: "exact", head: true }).eq("user_id", userId)
    ]);
    const summary = {
      email: ctx.getUserEmail(),
      username: profile?.username ?? null,
      total_album_ratings: count ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wyhogaetnnvbwnrjficz";
var mcp_default = defineMcp({
  name: "soundvault-mcp",
  title: "SoundVault",
  version: "0.1.0",
  instructions: "Tools for SoundVault, a music rating app. Use `search_music` to find artists/albums/tracks on Deezer, `rate_album` to record a 1-10 rating for the signed-in user, `list_my_ratings` to browse their rated albums, and `get_my_profile` for account info.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_music_default, list_my_ratings_default, rate_album_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
